#server:
# port: 8081
# path: /hello
#
#person:
# hobby:
#  play
#  read
#  sleep
#
#person:
# hobby: [sing,read,sleep]
#
#person:
# map:
#  k1: v1
#  k2: v2
#
#person:
# map: {k1: v1,k2: v2}

#对实体类对象Person进行属性设置
person:
 id: 2
 name: 张三
 hobby: [sing,read,sleep]
 family: [father,mother]
 map: {k1: v1,k2: v2}
 pet: {type: cat,name: tom}

examp:
 email: test
